enum BadgeRankAchievement {
  CURRENT_BADGE_RANK_MAX = 100,
  CURRENT_BADGE_RANK_HALF = 50,
  CURRENT_BADGE_RANK_TOP_TEN = 10,
  CURRENT_BADGE_RANK_FIRST = 1,
  CURRENT_BADGE_RANK_SECOND = 2,
  CURRENT_BADGE_RANK_THIRD = 3
}

export default BadgeRankAchievement