export const SCIENCE_TRAIN_ACTIVITY_ID =
  process.env.VUE_APP_SCIENCE_TRAIN_ACTIVITY_ID || "460544621232197";

// 正式活动的抽奖与报名、答题、积分、打卡和排行榜使用同一活动 ID。
// 保留抽奖环境变量以兼容现有构建配置，未配置时跟随主活动。
export const SCIENCE_TRAIN_LOTTERY_ACTIVITY_ID =
  process.env.VUE_APP_SCIENCE_TRAIN_LOTTERY_ACTIVITY_ID || SCIENCE_TRAIN_ACTIVITY_ID;

export const SCIENCE_TRAIN_ACTIVITY_NAME = "科普列车川渝黔行";

export const SICHUAN_SCIENCE_MUSEUM_ACTIVITY_ID = "849467725103173";
export const CHONGQING_SCIENCE_MUSEUM_ACTIVITY_ID = "847711669686341";
