enum MiniAppSceneEnum {
  NO_PUBLIC_PROFILE_PAGE_RELATED_APPLET_LIST= 1020,
  OFFICIAL_ACCOUNT_CUSTOM_MENU = 1035,
  APP_SHARE_MESSAGE_CARD,
  APPLET_OPEN_APPLET,
  RETURN_FROM_ANOTHER_APPLET,
  OFFICIAL_ACCOUNT_TEMPLATE_MESSAGE = 1043
}

export default MiniAppSceneEnum
